version: '3'
services:
  mongo:
    image: mongo:5.0
    container_name: my_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tonline
      MONGO_INITDB_ROOT_USERNAME: hadmin
      MONGO_INITDB_ROOT_PASSWORD: hadmin123
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: